### ISSUE TITLE
Media storage needs clean-up

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#35]
Hi.

All sent media is stored in `/media` folder.
It's getting larger and larger.
I can't find any case to use these files after they are sent and need to make clean-up on my own.

Maybe clean-up in callback?
Or timer clean-up?

Thanks.

**Comment by matteocontrini** [comment]
Hi,
what would you prefer? Would it be fine an "auto-deletion" of files older than one hour or something like that?

Let me know

**Comment by amozgachev** [comment]
Hi.

I think, the most useful way is to delete files in callback.
You don't reuse them even if the same url is provided, so you don't need to store them after successful callback.

For myself I made a clean-up script which starts every hour and removes files older than 2 hours.
But it isn't a good solution as whatsapi is stored deep in `/node-modules`.

**Comment by elad** [comment]
@matteocontrini the way files are handles should change so that they can be written wherever the user wants. It makes no sense to save these files inside the module directory. If you're open to that direction, I can work on a pull request to implement better handling.

More related to this PR, I think deletion should be handled strictly by user code and not the module.

**Comment by matteocontrini** [comment]
Of course, add a property in the config if you want (with the path to media).

**Comment by elad** [comment]
Where is it documented?

**Comment by matteocontrini** [comment]
What? The config?

https://github.com/hidespb/node-whatsapi/blob/master/whatsapi.js#L56
[Reference](https://github.com/hidespb/node-whatsapi/wiki/API-Reference#WhatsApiConfig)

**Comment by amozgachev** [comment]
Moreover, I think there is some bad logic now: sent files are stored and received are not.

**Comment by matteocontrini** [comment]
@amozgachev the files you send need to be downloaded locally before being sent to WhatsApp, that's why they are downloaded in a folder. Received files can be ignored if you are not interested in them, so they are not saved anywhere.

**Comment by elad** [comment]
@matteocontrini yes I saw both thing, where is the media path? :)

**Comment by matteocontrini** [comment]
@elad one is [here](https://github.com/hidespb/node-whatsapi/blob/master/extensions/media.js#L197), but honestly I can't tell you that's the only reference. The media part has been *nearly* untouched since it was first written by the owner of the repo

**Comment by elad** [comment]
@matteocontrini that's exactly what I'm saying. This logic does not involve the configuration at all:

```js
var filePath = path.join(__dirname, '../media', 'media-');
filePath += crypto.randomBytes(4).readUInt32LE(0) + ext;
```

I want to change it so that it, along with any other instances, do.

Will submit a pull request when I get a chance, hopefully sometime during the weekend.

**Comment by matteocontrini** [comment]
@elad in fact I've said "add a property to the config if you want", meaning adding a property to `defaultConfig`, not *setting* a property to the config parameter. I meant what you meant

**Comment by elad** [comment]
@matteocontrini ahhh, okay - so I understood you wrong, sorry for the noise!

**Comment by matteocontrini** [comment]
@elad my fault, I haven't been clear probably. Anyway, feel free to make improvements!

**Comment by matteocontrini** [comment]
Hey, anything new about this?

**Comment by elad** [comment]
@matteocontrini yes - I was wrong in my earlier comments because I thought *incoming* media wasn't being handled properly whereas it's actually *outgoing* media that's the problem.

What I'd like to do now then is add a dependency on [node-tmp](https://github.com/raszi/node-tmp) and instead of manually creating a file in a local media dir simply get one in the system's temporary file storage (e.g. /tmp). That at least puts temporary files in a place they have a better chance of getting cleaned up automatically.

Anyway, sorry for the delay, let me do a quick pull request right now. :)
