### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#64]
Hi There,

First of all i want to thank you guys for this great pice of code you build. Currently we are using this library within our app, everything works great unit today. We got an strange "index out of range" exception. Please note, we are using to receive (not sending) a lot of messages (like 30k+ messages each week), see our stack trace below. I didn`t find any issues related to this one, so i thought i share this one with you, so we could improve the code together. 

Hope to hear from you soon:)
Thanks in advance!

Uncaught Exception...
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt16BE (buffer.js:560:5)
    at Reader.peekInt16 (/public_html/node_modules/whatsapi/protocol.js:561:20)
    at Reader.nextNode (/public_html/node_modules/whatsapi/protocol.js:354:23)
    at WhatsApi.onTransportData (/public_html/node_modules/whatsapi/whatsapi.js:350:26)
    at Socket.<anonymous> (/public_html/node_modules/whatsapi/transport.js:26:52)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by matteocontrini** [comment]
With "until today" what do you mean? How long has the script been online before the error? Are you having the same issue now when you launch the application?

**Comment by timbersoen** [comment]
Excuse for my late response, i have been very busy lately. The script has been running for a few days. When i start the scrip again, everything works fine, but an couple of hours later i get the same exception. What does this exception even mean: "RangeError: index out of range"? Please let me know if you need some more info / logs.
Thanks in advance for your response!

**Comment by matteocontrini** [comment]
According to what you said, you are receive *more* than 3 messages *per second*. That's clearly not a normal usage of WhatsApp. And it's not even normal that a WhatsApp instance/connection is kept open for hours or days.
The solution is using the API in a regular way, or ignoring the error. With that usage something can go wrong, precisely because you are exchanging **a lot** of nodes on the *same* connection. So, drop the connection and establish it again every now and then, or ignore the errors and make the script restart when it fails. Reconnection is the only way to reset the connection.

That's all we can do.
